name: Actualizar Standings de Dota 2

on:
  schedule:
    # Se ejecuta cada 15 minutos
    - cron: '*/15 * * * *'
  # Permite ejecutarlo manualmente desde GitHub
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar Dependencias
        run: npm install jsdom

      - name: Ejecutar Script de Extracción
        run: node update-standings.js

      - name: Guardar y Hacer Commit en GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add standings.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "bot: actualización automática de standings.json" && git push)
